# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-01 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, unique=True, verbose_name='name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='SubAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, unique=True, verbose_name='name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_modified', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('checked_out', models.BooleanField(default=False)),
                ('location', models.FilePathField()),
            ],
        ),
    ]
