# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-01 04:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasset',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_asset_creator', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='subasset',
            name='current_checked_out_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_owner', to=settings.AUTH_USER_MODEL, verbose_name='temp-owner'),
        ),
        migrations.AddField(
            model_name='subasset',
            name='current_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Department'),
        ),
        migrations.AddField(
            model_name='subasset',
            name='parent_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_creator', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='asset',
            name='current_department',
            field=models.ManyToManyField(to='departments.Department', verbose_name='list of departments'),
        ),
        migrations.AddField(
            model_name='asset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
