# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-08 05:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20160401_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='current_department',
            field=models.ManyToManyField(blank=True, to='departments.Department', verbose_name='list of departments'),
        ),
        migrations.AlterField(
            model_name='subasset',
            name='current_checked_out_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_owner', to=settings.AUTH_USER_MODEL, verbose_name='temp-owner'),
        ),
    ]
