# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-07 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_auto_20160407_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='project',
            field=models.ManyToManyField(blank=True, to='projects.Project', verbose_name='list of projects'),
        ),
    ]
