# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-08 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_current_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='current_project',
            field=models.ManyToManyField(blank=True, to='projects.Project'),
        ),
    ]
