# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-19 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, unique=True, verbose_name='name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('address', models.CharField(max_length=40, verbose_name='address')),
                ('state', models.CharField(max_length=2, verbose_name='state')),
                ('zip', models.CharField(max_length=5, verbose_name='zip')),
                ('city', models.CharField(max_length=20, verbose_name='city')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
